habitat_baselines:
  trainer_name: ppo
  torch_gpu_id: 0
  video_render_views: []
  tensorboard_dir: tb
  writer_type: wb
  video_dir: video_dir
  video_fps: 10
  test_episode_count: -1
  eval_ckpt_path_dir: data/new_checkpoints
  num_environments: 10
  num_processes: -1
  checkpoint_folder: data/new_checkpoints
  num_updates: 5000
  num_checkpoints: 20
  checkpoint_interval: -1
  total_num_steps: -1.0
  log_interval: 25
  video_interval: 150
  log_file: train.log
  force_blind_policy: false
  verbose: false
  eval_keys_to_include_in_name: []
  force_torch_single_threaded: true
  wb:
    project_name: ''
    entity: ''
    group: ''
    run_name: ''
    run_id: ''
  load_resume_state_config: true
  eval:
    split: val
    use_ckpt_config: true
    should_load_ckpt: true
    evals_per_ep: 1
    video_option: []
  profiling:
    capture_start_step: -1
    num_steps_to_capture: -1
  launch_eval_afterwards: true
  rl:
    preemption:
      append_slurm_job_id: false
      save_resume_state_interval: 100
      save_state_batch_only: false
    policy:
      name: PointNavResNetPolicy
      action_distribution_type: categorical
      action_dist:
        use_log_std: true
        use_softplus: false
        std_init: ???
        log_std_init: 0.0
        use_std_param: false
        clamp_std: true
        min_std: 1.0e-06
        max_std: 1
        min_log_std: -5
        max_log_std: 2
        action_activation: tanh
        scheduled_std: false
      obs_transforms: {}
      hierarchical_policy: ???
    ppo:
      clip_param: 0.2
      ppo_epoch: 4
      num_mini_batch: 2
      value_loss_coef: 0.5
      entropy_coef: 0.01
      lr: 0.00025
      eps: 1.0e-05
      max_grad_norm: 0.5
      num_steps: 128
      use_gae: true
      use_linear_lr_decay: true
      use_linear_clip_decay: true
      gamma: 0.99
      tau: 0.95
      reward_window_size: 50
      use_normalized_advantage: false
      hidden_size: 512
      entropy_target_factor: 0.0
      use_adaptive_entropy_pen: false
      use_clipped_value_loss: true
      use_double_buffered_sampler: false
    ddppo:
      sync_frac: 0.6
      distrib_backend: GLOO
      rnn_type: GRU
      num_recurrent_layers: 1
      backbone: resnet18
      pretrained_weights: data/ddppo-models/gibson-2plus-resnet50.pth
      pretrained: false
      pretrained_encoder: false
      train_encoder: true
      reset_critic: true
      force_distributed: false
    ver:
      variable_experience: true
      num_inference_workers: 2
      overlap_rollouts_and_learn: false
    auxiliary_losses: {}
habitat:
  seed: 100
  env_task: GymHabitatEnv
  env_task_gym_dependencies: []
  env_task_gym_id: ''
  environment:
    max_episode_steps: 256
    max_episode_seconds: 10000000
    iterator_options:
      cycle: true
      shuffle: true
      group_by_scene: true
      num_episode_sample: -1
      max_scene_repeat_episodes: -1
      max_scene_repeat_steps: 10000
      step_repetition_range: 0.2
  simulator:
    type: Sim-v0
    action_space_config: v0
    action_space_config_arguments: {}
    forward_step_size: 0.3
    create_renderer: false
    requires_textures: true
    auto_sleep: false
    step_physics: true
    concur_render: false
    needs_markers: true
    update_robot: true
    scene: data/scene_datasets/habitat-test-scenes/van-gogh-room.glb
    scene_dataset: default
    additional_object_paths: []
    seed: ${habitat.seed}
    turn_angle: 30
    tilt_angle: 15
    default_agent_id: 0
    debug_render: false
    debug_render_robot: false
    kinematic_mode: false
    debug_render_goal: true
    robot_joint_start_noise: 0.0
    ctrl_freq: 120.0
    ac_freq_ratio: 4
    load_objs: false
    hold_thresh: 0.15
    grasp_impulse: 10000.0
    agents:
      main_agent:
        height: 0.4
        radius: 0.35
        sim_sensors:
          rgb_sensor:
            type: HabitatSimRGBSensor
            height: 144
            width: 256
            position:
            - 0.0
            - 0.4
            - 0.0
            orientation:
            - 0.0
            - 0.0
            - 0.0
            hfov: 69
            sensor_subtype: PINHOLE
            noise_model: None
            noise_model_kwargs: {}
          depth_sensor:
            type: HabitatSimDepthSensor
            height: 144
            width: 256
            position:
            - 0.0
            - 0.4
            - 0.0
            orientation:
            - 0.0
            - 0.0
            - 0.0
            hfov: 87
            sensor_subtype: PINHOLE
            noise_model: None
            noise_model_kwargs: {}
            min_depth: 0.0
            max_depth: 10.0
            normalize_depth: true
        is_set_start_state: false
        start_position:
        - 0.0
        - 0.0
        - 0.0
        start_rotation:
        - 0.0
        - 0.0
        - 0.0
        - 1.0
        joint_start_noise: 0.1
        robot_urdf: data/robots/hab_fetch/robots/hab_fetch.urdf
        robot_type: FetchRobot
        ik_arm_urdf: data/robots/hab_fetch/robots/fetch_onlyarm.urdf
    agents_order:
    - main_agent
    habitat_sim_v0:
      gpu_device_id: 0
      gpu_gpu: false
      allow_sliding: true
      frustum_culling: true
      enable_physics: false
      physics_config_file: ./data/default.physics_config.json
      leave_context_with_background_renderer: false
      enable_gfx_replay_save: false
    ep_info: null
  task:
    reward_measure: distance_to_goal_reward
    success_measure: euclidean_success
    success_reward: 2.5
    slack_reward: -0.003
    end_on_success: true
    type: TargetNav-v0
    lab_sensors: {}
    measurements:
      distance_to_goal:
        type: DistanceToGoal
        distance_to: POINT
      euclidean_distance_to_goal:
        type: EuclideanDistanceToGoal
      euclidean_success:
        type: EuclideanSuccess
        success_distance: 0.4
      nonstop_euclidean_success:
        type: NonStopEuclideanSuccess
        success_distance: 0.4
      euclidean_spl:
        type: EuclideanSPL
      nonstop_euclidean_spl:
        type: NonStopEuclideanSPL
      distance_to_goal_reward:
        type: DistanceToGoalReward
      top_down_map:
        type: TopDownMap
        max_episode_steps: 256
        map_padding: 3
        map_resolution: 1024
        draw_source: true
        draw_border: true
        draw_shortest_path: true
        draw_view_points: true
        draw_goal_positions: true
        draw_goal_aabbs: true
        fog_of_war:
          draw: true
          visibility_dist: 5.0
          fov: 90
    goal_sensor_uuid: pointgoal
    count_obj_collisions: true
    settle_steps: 5
    constraint_violation_ends_episode: true
    constraint_violation_drops_object: false
    force_regenerate: false
    should_save_to_cache: false
    must_look_at_targ: true
    object_in_hand_sample_prob: 0.167
    min_start_distance: 3.0
    render_target: true
    physics_stability_steps: 1
    num_spawn_attempts: 200
    spawn_max_dists_to_obj: 2.0
    base_angle_noise: 0.523599
    ee_sample_factor: 0.2
    ee_exclude_region: 0.0
    base_noise: 0.05
    spawn_region_scale: 0.2
    joint_max_impulse: -1.0
    desired_resting_position:
    - 0.5
    - 0.0
    - 1.0
    use_marker_t: true
    cache_robot_init: false
    success_state: 0.0
    easy_init: false
    should_enforce_target_within_reach: false
    task_spec_base_path: habitat/task/rearrange/pddl/
    task_spec: ''
    pddl_domain_def: replica_cad
    obj_succ_thresh: 0.3
    enable_safe_drop: false
    art_succ_thresh: 0.15
    robot_at_thresh: 2.0
    filter_nav_to_tasks: []
    actions:
      stop:
        type: StopAction
      move_forward:
        type: MoveForwardAction
      turn_left:
        type: TurnLeftAction
      turn_right:
        type: TurnRightAction
  dataset:
    type: TargetNav-v0
    split: train
    scenes_dir: data/scene_datasets
    content_scenes:
    - '*'
    data_path: data/datasets/targetnav/meeting_room_w_ceiling/random/{split}/{split}.json.gz
  gym:
    auto_name: ''
    obs_keys: null
    action_keys: null
    achieved_goal_keys: []
    desired_goal_keys: []
