ros2 topic pub --once /move com304_interfaces/msg/Move "{x: 0.5, y: 0}"
ros2 topic pub --once /rotate com304_interfaces/msg/Rotate "{yaw: 1.57}"
ros2 topic pub --once /move com304_interfaces/msg/Move "{x: 0.5, y: 0}"
ros2 topic pub --once /rotate com304_interfaces/msg/Rotate "{yaw: 1.57}"
ros2 topic pub --once /move com304_interfaces/msg/Move "{x: 0.5, y: 0}"
ros2 topic pub --once /rotate com304_interfaces/msg/Rotate "{yaw: 1.57}"
ros2 topic pub --once /move com304_interfaces/msg/Move "{x: 0.5, y: 0}"
ros2 topic pub --once /rotate com304_interfaces/msg/Rotate "{yaw: 1.57}"